pluginManagement {
    // Resolve the Flutter SDK location.
    //
    // 1. `android/local.properties` (generated by `flutter pub get` / `flutter build`).
    // 2. The `FLUTTER_ROOT` environment variable, which the Flutter tooling and
    //    `subosito/flutter-action` both export in CI.
    //
    // Falling back to the env var matters: running `./gradlew :core-engine:test`
    // on a clean checkout (or in CI) used to blow up with a
    // FileNotFoundException because local.properties had not been created yet.
    val flutterSdkPath =
        run {
            val properties = java.util.Properties()
            val localProperties = file("local.properties")
            if (localProperties.exists()) {
                localProperties.inputStream().use { properties.load(it) }
            }
            val fromProperties = properties.getProperty("flutter.sdk").orEmpty().trim()
            val resolved = fromProperties.ifEmpty { System.getenv("FLUTTER_ROOT").orEmpty().trim() }
            require(resolved.isNotEmpty()) {
                "Unable to locate the Flutter SDK. Set `flutter.sdk` in android/local.properties " +
                    "(run `flutter pub get` from the repository root) or export FLUTTER_ROOT."
            }
            resolved
        }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.application") version "8.13.0" apply false
    id("com.android.library") version "8.13.0" apply false
    // Kotlin 2.x is required: both `:app` and `:core-engine` configure the
    // compiler through the `kotlin { compilerOptions { … } }` DSL, which only
    // exists from Kotlin Gradle Plugin 2.0 onwards. 2.4.0 is the KGP that
    // Flutter 3.47.6 pins in its own app template, and it is the newest KGP
    // whose documented AGP range (8.2.2..<9.2.99) contains 8.13.0.
    id("org.jetbrains.kotlin.android") version "2.4.0" apply false
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

include(":app")
include(":core-engine")
project(":core-engine").projectDir = file("core-engine")
